### ISSUE TITLE
[Feature Request] Add PDF/Excel Export

### ISSUE THREAD

**Issue by bjesuiter** [antonycourtney/tad#142]
Hey there, 

thank you for your awesome work! 
I use Tad to filter & polish csv files with my worklogs to provide some nice worklog pdf to my client. 

Unfortunately I can't export the filtered / sorted and pivoted dataset to pdf for providing it to my client. 
But I understand that the focus of your tool is not to be an export tool with formatting. 

So I would also be finde with having an export to Excel, with which I can do the formatting and export later :) 
the problem currently is, that my csv has commas instead of semicolons and the encoding does not match with my excel, so i can't simply import the filtered csv in my Excel.

**Comment by chengjie0929** [comment]
Cannot export directly from duckdb database to csv format

**Comment by bjesuiter** [comment]
Since I don't need this anymore, I'll close this issue
