### ISSUE TITLE
How is tad licensed? 

### ISSUE THREAD

**Issue by timvw** [antonycourtney/tad#181]
Can't find a license ... The modules do state they are under an "MIT" license

**Comment by ad-si** [comment]
@antonycourtney It would still be good to add a license file to the repo, right?

**Comment by antonycourtney** [comment]
@timvw @ad-si Sorry for the long delay. The missing LICENSE file was pure oversight on my part; I think I forgot to include it when I did a major restructuring of the git repository last year. Just added it back (MIT Licensed, of course). Thanks.
