### ISSUE TITLE
DuckDB 0.6.0 not supported (Windows)

### ISSUE THREAD

**Issue by HellLeaf** [antonycourtney/tad#186]
When opening file created with duckdb version 0.6.0 then error is shown:

[Window Title]
Error

[Main Instruction]
Error initializing Tad

[Content]
IO Error: Trying to read a database file with version number 39, but we can only read version 33.
The database file was created with an newer version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

[OK]
--------------
Windows version 10
Tad - latest prebuild binaries: 0.10.1

**Comment by HellLeaf** [comment]
Closing this as v.0.11.0 fixes the issue.

**Comment by chengjie0929** [comment]
Plesase add the function of directly exporting data from the database to csv format.

**Comment by chengjie0929** [comment]
Please add the function of directly exporting data from the database to csv format.
