### ISSUE TITLE
Do Tad Support Visualization

### ISSUE THREAD

**Issue by akash-goel** [antonycourtney/tad#195]
Hi Team,

we would like to check that do Tad Supports Visualization like Bar Chart , Pie Chart , Sankey Diagram , Sun burst ?

Regards,
Akash

**Comment by antonycourtney** [comment]
Hi Akash,

Tad does not currently support visualizations. I'd like to get some basic visualization capabilities added someday, but it's a substantial undertaking.
Best,
   -Antony
