### ISSUE TITLE
DuckDB 0.7

### ISSUE THREAD

**Issue by stuta** [antonycourtney/tad#205]
This does not work with the latest DuckDB.

**Comment by sfd99** [comment]
Yes, same here. 
TAD does not work
w/t he latest version of DUCKDB 0.7...  :-(

Antony, HELP!!
TAD is so great.

**SFd99
San Francisco**
Ubuntu Linux
Rstudio
latest TAD Viewer installed f/DEB file...
(with CSVs it works ok).

**Comment by sfd99** [comment]
**_Thanks, Antony!._**
So far,
smooth sailing with TAD 0.12.0 
(for CSV, DuckDB 0.7.1, SQLite files). 

What a great app
 with an _excellent_ UI...

**SFd99
San Francisco
Ubuntu Linux
R, Rstudio
latest TAD Viewer 0.12.0 :-)
(installed f/ .DEB file...).**
