### ISSUE TITLE
Feature Request: Ability to Work Offline 

### ISSUE THREAD

**Issue by cherzog** [antonycourtney/tad#234]
I need to run TAD on a fully offline PC. But, there are downloads in the Background. This is not possible on the environment. 

It would be nice, the install-file comes with all dependencies or there is a how-to-guide which describes the process to manually copy the dependencies to the right location.

**Comment by antonycourtney** [comment]
This should be the same issue as #210. A candidate fix is already landed, so hopefully this will be resolved in the next release of Tad.

**Comment by antonycourtney** [comment]
@cherzog - This should be resolved with [Tad 0.13.0](https://github.com/antonycourtney/tad/releases/tag/v0.13.0), released yesterday. Would be grateful if you could confirm this release resolves the issue.
