### ISSUE TITLE
"no newline found" - BUFSIZE of 1024 too small for long headers

### ISSUE THREAD

**Issue by simonpercivall** [antonycourtney/tad#40]
For CSVs with long headers, reading 1024 characters for the header row may be too conservative. In fact, the header row of the first CSV I tried opening with Tad has a length of just under 4000 characters.

**Comment by antonycourtney** [comment]
Well spotted - thank you!

**Comment by antonycourtney** [comment]
@simonpercivall - Going to bump this to 8K and close the issue for now. Hope to issue a new point release in the next few days. Please feel free to re-open the issue if this proves insufficient in your use cases. Thanks.

**Comment by antonycourtney** [comment]
Fixed (for now) by 5b6b25d82411763d129228e1862a747141c4d9ef
