### ISSUE TITLE
pivot problem with imdb metadata 

### ISSUE THREAD

**Issue by mjg232** [antonycourtney/tad#46]
tried to pivot by color, country, release year, director and got this error that I couldn't dismiss
<img width="1205" alt="screenshot 2017-04-10 09 35 49" src="https://cloud.githubusercontent.com/assets/15220751/24864199/6d794dda-1dd1-11e7-8a53-9cb3e8ef72d0.png">

**Comment by antonycourtney** [comment]
Yikes! Thanks for reporting, will take a look.
