### ISSUE TITLE
It works on Linux?

### ISSUE THREAD

**Issue by kguidonimartins** [antonycourtney/tad#49]

**Comment by antonycourtney** [comment]
Work in progress!  I posted [a Tweet](https://twitter.com/antonycourtney/status/863772343742550016) earlier today showing that I got it building and running succesfully on Linux.  Working now on packaging it all up reasonably.

I will post a note to the [Tad mailing list](http://tadviewer.com/#contact) when a packaged release is available for Linux.

**Comment by antonycourtney** [comment]
Latest release (0.8.4) includes a Linux build as a .deb package.
