### ISSUE TITLE
Support multiple CSV dialects

### ISSUE THREAD

**Issue by briatte** [antonycourtney/tad#52]
European-style CSV uses semicolons for separators and commas for floats.

Example (saved from R, thus the last two column formats):

```
"";"id";"float";"name";"date";"logical"
"1";"10000";0,189614180182718;"a b";2015-04-05;FALSE
"2";"10001";-0,445634937641628;"c d";2015-03-12;FALSE
"3";"10001";-0,557006757297433;"e f";2015-04-05;TRUE
```

Reads fine with a QuickLook CSV viewer:

![screen shot 2017-05-17 at 19 23 07](https://cloud.githubusercontent.com/assets/322533/26167212/80109cf0-3b36-11e7-82ed-0401afa26ef6.png)

Yet will crash Tad:

![screen shot 2017-05-17 at 19 25 07](https://cloud.githubusercontent.com/assets/322533/26167229/8ebc5050-3b36-11e7-9e4a-7ebe1481c789.png)

**Comment by rhlff** [comment]
I would like to even extend this request, to configure separators in a more generic way. Like in MS Excel, it would be nice to choose the separator key manually, like tabs, commas, semicolons, white spaces or any other symbol. Additionally, it would be nice to configure a surrounding symbol that protects strings to be separated, like `"` in `"this is one column value"`.

**Comment by colinscroggins** [comment]
@rhlff The overarching concept of CSV dialect support might be useful. Look at how the following project documents it. The question is whether to force all users through manually selecting it or default to the common cases (comma and tab) and then provide a manual import option for everybody else.

http://specs.frictionlessdata.io/csv-dialect/

**Comment by rhlff** [comment]
@colinscroggins thanks for the link, this is exactly what I tried to describe. Imho the second option would be more convenient for most users.

**Comment by foto-andreas** [comment]
configure the separators is a must

**Comment by TimothyBramlett** [comment]
@antonycourtney Is there any documentation on how to specify the delimiter?  I can't find any.
