### ISSUE TITLE
Can't open CSV files with more than 8192 (2^13) bytes of headers

### ISSUE THREAD

**Issue by jiaaro** [antonycourtney/tad#81]
I have access to a database with - *ahem* - a lot of key/value pairs which are exportable as a table and the headers line is routinely longer than 8192 bytes.

When trying to open these CSV files I see the following:

<img width="532" alt="screen shot 2017-05-31 at 5 39 12 pm" src="https://cloud.githubusercontent.com/assets/232593/26655251/138f372e-4628-11e7-8400-b0ba7cd693ed.png">

Manually trimming the headers line to 8191 bytes gets Tad to successfully open the file (at the expense of losing a bunch of columns)

Opening a few random files on my desktop in BBEdit shows that 52349 bytes in the headers line is not uncommon. 2^16 bytes would handle that file, though 2^18 leaves a comfortable margin for uncommonly large exports 😁

**Comment by jiaaro** [comment]
Searching around the code a bit turned this up:
https://github.com/antonycourtney/tad/blob/master/src/csvimport.js#L427

Probably just need to increase the buffer size - I'm not sure what tradeoffs are involved, but it seems like reading 100k is not a big deal on modern systems especially the ones used by data scientists

**Comment by antonycourtney** [comment]
Hi @jiaaro Well spotted!  Yes, you're exactly right, just a naieve assumption on my part baked into the code.  Will contemplate the right fix; I agree a one-off 100KB is no big deal.

**Comment by antonycourtney** [comment]
Should be fixed by recent commits, which re-worked header input to read using stream instead of fixed size buffer (for other reasons).  Closing for now, please re-open if not resolved once 0.8.5 is released.
