### ISSUE TITLE
Copy takes wrong cells after column re-order

### ISSUE THREAD

**Issue by hmontenegro** [antonycourtney/tad#82]
Tad 0.8.4
After a hide / show / visual reordering of the columns, copying and pasting a few cells over some columns, what is sent to the clipboard are the original columns, not the ones being visually selected.

**Comment by hmontenegro** [comment]
#44 maybe linked to this

**Comment by antonycourtney** [comment]
Also reported by Carl Witt to tad-feedback:

```
The bug I found is that copying from a pivoted table gives strange data. It’s in the right format (e.g., I select 2x3 cells, I get 2x3 values) but I don’t get the pattern where the data’s taken from.  

- if I turn off the pivoting and the sorting, it works
- if I sort by a column or turn on pivoting, copying doesn’t produce sensible results anymore

It’s Version 0.8.4 on a Mac. 
```

**Comment by antonycourtney** [comment]
Simple repro: 
- open bart-comp-all
- Pivot by name
- copy a few rows and columns Name, Title, Base
- paste into text editor
Should get cells we copied.
Instead get: columns Title, Base, OT
