### ISSUE TITLE
Virus in Windows installer detected

### ISSUE THREAD

**Issue by clicks** [antonycourtney/tad#84]
Trendmicro Worry Free Business Security and VirusTotal detect a virus/ransomware in the  Windows Setup file:
https://www.virustotal.com/file/8954228c0163ab8cb6d235315fb6a1dc023c4af5a0faff686f9976bfa17e8793/analysis/

**Comment by antonycourtney** [comment]
Thanks for reporting.  I strongly suspect this is a false positive; I did the build myself on a fresh Windows 10 VM that has no other software installed.  Any ideas or suggestions on how to follow up on this?

**Comment by clicks** [comment]
Sorry can't give any advice in this direction. All other Google hits regarding this virus detection by Bkav were false positives. Actually VirusTotal doesn't find anything by now. So I think this could be closed. 
Self healing problems 👍

**Comment by antonycourtney** [comment]
Thank you for doing that extra level of investigation, and for bringing this to my attention in the first place. Very much appreciated!
