### ISSUE TITLE
Installing on Windows 7 with out Admin rights

### ISSUE THREAD

**Issue by sahajamit** [antonycourtney/tad#96]
Is there any way to install it on Windows 7 with out having admin rights.

**Comment by derekmcloughlin** [comment]
Bump. This can't be installed in most large enterprises because they generally don't give devs admin permissions on their devices. A ZIP file with the install would be great.

**Comment by fgenoese** [comment]
also interested in this

**Comment by luk-f-a** [comment]
hi, I also want to test it on a corporate laptop and I cannot install it.

**Comment by antonycourtney** [comment]
Fixed in 0.10.1 (to be released today). Installer should now give an option on whether to install for all users or just the current user.

**Comment by antonycourtney** [comment]
@fgenoese @luk-f-a 0.10.1 is now out, available at https://github.com/antonycourtney/tad/releases/tag/v0.10.1. Please give it a try and let me know if this resolves the issue for you.

**Comment by derekmcloughlin** [comment]
Yep, this installs correctly without admin rights. Thanks.
