### ISSUE TITLE
Can't paste into Filter's "Value" field

### ISSUE THREAD

**Issue by ariutta** [antonycourtney/tad#99]
Observed on tad version 0.8.4 on macOS 10.12.5.

Steps to repro:
* click "Filter"
* select a column and an operator
* Copy text from anywhere and try pasting it into the "Value" field

Pasting does nothing. It is, however, possible to type into the field.

**Comment by taohex** [comment]
I need this feature, too!

**Comment by sebfie** [comment]
+1

**Comment by newtoncalegari** [comment]
I'm using the version 0.9.0 on Mac OS X 10.14.5 and it's not possible to paste any content on TAD.
I've tried pasting it into the "Value" field and into the Developer Tools console and it also didn't work.

**Comment by natanlao** [comment]
I can still reproduce this on v0.9.0, macOS 10.15.7

**Comment by CiaranMcCann** [comment]
Yeah makes this unusable really being unable to copy and paste values in and out of it. I'm also able to repo it on v0.9.0, macOS 10.13.6

**Comment by RubenR1** [comment]
+1

**Comment by carsonbland** [comment]
+1

**Comment by lcamaione** [comment]
+1

**Comment by carsonbland** [comment]
Still an issue in version 0.10.0

**Comment by antonycourtney** [comment]
Embarassing that this papercut has been lingering so long. Fix forthcoming.
